baseURL = 'https://blog.dsnb.cc/'
defaultContentLanguage = "zh"
languageCode = 'zh-Hans'
title = "DongShaoNB's Blog"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true

[markup]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "DongShaoNB"
description = "东少的笔记本"
avatar = "avatar.jpg"
headerTitle = "DongShaoNB's Blog"
motto = "喜欢就坚持下去吧！"

rss = true

utterancesRepo = "DongShaoNB/MyBlog"

email = "i@dsnb.cc"
 
siteStartYear = 2024
 
favicon = '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%2210 0 100 100%22><text y=%22.90em%22 font-size=%2290%22>❤️</text></svg>"></link>'

customSyntaxHighlighting = true

stickyNav = true
reorderNavItems = ["search", "github"]
collapseNavItems = ["categories", "tags", "posts", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderShares = ["x"]

[params.navItems]
github = { href = "https://github.com/DongShaoNB/MyBlog", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"